### ISSUE TITLE
Manual Install

### ISSUE THREAD

**Issue by drogojinaru** [soffes/Crypto#33] opened 2017-07-12 12:48 UTC
Ho can I Install it manually, i have some problems with that...

**Comment by soffes** [comment] 2017-11-22 05:30
This isn't supported since it's kind of complicated. I'd recommend using Carthage. Sorry.

**Comment by soffes** [comment] 2017-11-22 05:30
This is a duplicate of #31. I guess I should write this up since multiple people asked for it :P

**Closed as completed by soffes** 2017-11-22 05:30 UTC
